base_images:
  base:
    name: "4.5"
    namespace: ocp
    tag: base
  registration:
    name: "4.5"
    namespace: open-cluster-management
    tag: registration
  registration-operator:
    name: "4.5"
    namespace: open-cluster-management
    tag: registration-operator
  registration-operator-src:
    name: "4.5"
    namespace: open-cluster-management
    tag: registration-operator
  work:
    name: "4.5"
    namespace: open-cluster-management
    tag: work
binary_build_commands: make build
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.13
promotion:
  name: "4.6"
  namespace: ocp
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tag_specification:
  name: "4.6"
  namespace: ocp
test_binary_build_commands: make test
tests:
- as: unit
  commands: make test-unit
  container:
    from: bin
- as: e2e
  steps:
    cluster_profile: aws
    test:
    - as: deploy
      commands: |
        curl https://mirror.openshift.com/pub/openshift-v4/clients/oc/4.4/linux/oc.tar.gz | tar xvzf - oc
        KUBECTL=oc
        OLM_NAMESPACE=openshift-operator-lifecycle-manager
        IMAGE_NAME=${IMAGE_FORMAT//\/stable:\$\{component\}//pipeline:registration-operator}
        REGISTRATION_IMAGE=${IMAGE_FORMAT//\/stable:\$\{component\}//pipeline:registration}
        WORK_IMAGE=${IMAGE_FORMAT//\/stable:\$\{component\}//pipeline:work}
        PATH=.:$PATH
        export KUBECTL OLM_NAMESPACE PATH IMAGE_NAME REGISTRATION_IMAGE WORK_IMAGE
        make deploy-hub e2e-bootstrap-secret
      from: registration-operator-src
      resources:
        limits:
          memory: 4Gi
        requests:
          cpu: 100m
          memory: 200Mi
    - as: e2e-test
      commands: |
        export IMAGE_NAME=${IMAGE_FORMAT//\/stable:\$\{component\}//pipeline:registration}
        /e2e.test -test.v -ginkgo.v
      from: registration
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
zz_generated_metadata:
  branch: master
  org: open-cluster-management
  repo: rcm-controller
